### ISSUE TITLE
metric-proxy pod metrics unable to fetch from prometheus in cf-for-k8s v0.6.0

### ISSUE THREAD

**Issue by PavanVasist** [cloudfoundry/metric-proxy#8] opened 2020-09-08 06:09 UTC
## Describe the bug
metrics exposed from metric-proxy at port 9090 are reachable in localhost(0:9090 ---> inside the pod). But not able to reach from outside. Whereas the metrics from instio-proxy container within the pod(http://<metric-proxy-pod-IP>:15090/stats/prometheus) am able to fetch from outside(from prometheus pod).

## To Reproduce*
1. ssh into metric-proxy container within cf-system namespace and curl for 0:9090/metrics. We will be able get it.
2. Now ssh into other pod either within same namespace(cf-api-server pod) or into prometheus pod and try scraping the metrics, when doing it via prometheus pod running in different namespace we get -  
```
Get http://100.96.33.144:9090/metrics: context deadline exceeded
```
scraping via cf-api-server container within same namespace(cf-system), we get - 
```
curl: (56) Recv failure: Connection reset by peer
```

## Expected behavior
Metrics should have been scraped from 9090 port as it was able to from 15090.

### cf-for-k8s SHA 
_https://github.com/cloudfoundry/cf-for-k8s/commit/7c65597af7a4de935994813658a5db182fbecac9_

### Deploy instructions
_Deploying the release with default configurations with incluster persistence_

### Cluster information
_Using Gardener for creation of K8s cluster_

### CLI versions
_paste output of the following commands_

1. `ytt --version`: 0.30.0
2. `kapp --version`:0.33.0
3. `kubectl version`: 
```
lient Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.8", GitCommit:"35dc4cdc26cfcb6614059c4c6e836e5f0dc61dee", GitTreeState:"clean", BuildDate:"2020-06-26T03:36:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
4. `cf version`:6.52.0+b086fe522.2020-08-26

**Comment by kkburr** [comment] 2020-09-08 21:14
@PavanVasist Can you give us more clarity on how you deployed prometheus? Were you using the instructions in [cf-for-k8s-metrics-examples](https://github.com/cloudfoundry/cf-for-k8s-metric-examples), [cf-k8s-prometheus](https://github.com/cloudfoundry/cf-k8s-prometheus) or by another means?

**Comment by PavanVasist** [comment] 2020-09-09 03:18
Hi @kkburr - We had the below setup for prometheus.
- Deployed prometheus in another(**monitoring**) namespace using [helm chart ](https://github.com/helm/charts/tree/master/stable/prometheus)

- Created respective NetworkPolicy to allow prometheus to scrape from cf-system namespace.

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scrape
  namespace: cf-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          purpose=monitoring
      podSelector:
        matchLabels:
          app=prometheus
```

- Prometheus image version - ```prom/prometheus:v2.16.0```

**Comment by heycait** [comment] 2020-09-09 16:53
Regarding your prometheus deployed into another namespace, you'd have to update the [existing network policy on metric-proxy](https://github.com/cloudfoundry/cf-for-k8s/blob/57d45ed4fde555d85b11b690434d8ab63a42cb0a/config/networking/network-policies.yaml#L655-L677) to include ingress from your prometheus. 

The NetworkPolicy shared above doesn't appear to be a valid manifest when I try to deploy it. The labels should use colons instead of equals.

I was able to to partially reproduce your error, however when exec'd onto the cf-api-server pod, I got the following error instead:
```
curl: (52) Empty reply from server
```

To fix this, I added an extra istio annotation `traffic.sidecar.istio.io/excludeInboundPorts: "<metrics-port>"` to exclude the metric-proxy from istio mTLS and was able to curl the metric-proxy metrics endpoint via the cf-api-server pod. However, please note, that we've working on making Prometheus completely compatible with Istio. 

We recently committed this change: https://github.com/cloudfoundry/cf-k8s-prometheus/commit/bf9d5dfa4a526c3b7b7fa098795f91df30c96f75 which would allow you to see metric-proxy and uaa metrics. Be aware that because the cf-api-server is currently using the `traffic.sidecar.istio.io/excludeInboundPorts: "<metrics-port>"` annotation, you won't be able to reach CAPI's metrics until you remove that.

We do intend to include Prometheus in cf-for-k8s but this is still a work in process.

**Comment by PavanVasist** [comment] 2020-09-10 07:29
It's good to hear that prometheus support is coming by default with cf-for-k8s:)...

I added the annotation  ```traffic.sidecar.istio.io/excludeInboundPorts: "9090" ``` to **metrics-proxy** pod and then did a ```curl``` from **cf-ap-server** pod. Still no luck. We are using ```cf-for-k8s v0.6.0``` Anything else am i missing.

**Comment by heycait** [comment] 2020-09-10 15:20
Can you share the entire updated deployment manifest for metric-proxy?

**Comment by PavanVasist** [comment] 2020-09-11 02:59
PFB the same - 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kapp.k14s.io/change-rule.istio-sidecar-injector: upsert after upserting cf-for-k8s.cloudfoundry.org/istio-sidecar-injector
    kapp.k14s.io/identity: v1;cf-system/apps/Deployment/metric-proxy;apps/v1
    kapp.k14s.io/original: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kapp.k14s.io/change-rule.istio-sidecar-injector":"upsert
      after upserting cf-for-k8s.cloudfoundry.org/istio-sidecar-injector"},"labels":{"app":"metric-proxy","kapp.k14s.io/app":"1598428386871241000","kapp.k14s.io/association":"v1.19fde1e94b7fc26272a00c0d1d0decbc"},"name":"metric-proxy","namespace":"cf-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"metric-proxy","kapp.k14s.io/app":"1598428386871241000"}},"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"9090","prometheus.io/scrape":"true"},"labels":{"app":"metric-proxy","kapp.k14s.io/app":"1598428386871241000","kapp.k14s.io/association":"v1.19fde1e94b7fc26272a00c0d1d0decbc"}},"spec":{"containers":[{"env":[{"name":"ADDR","value":":8080"},{"name":"APP_SELECTOR","value":"cloudfoundry.org/guid"},{"name":"NAMESPACE","value":"cf-workloads"},{"name":"QUERY_TIMEOUT","value":"5"},{"name":"CA_PATH","value":"/ca/tls.crt"},{"name":"CERT_PATH","value":"/metric-proxy-certs/tls.crt"},{"name":"KEY_PATH","value":"/metric-proxy-certs/tls.key"}],"image":"oratos/metric-proxy@sha256:938ac36f0f1ede38b1ed7b2451b918345709848fc807a11500fd9b1b05fd239d","imagePullPolicy":"Always","name":"metric-proxy","ports":[{"containerPort":8080},{"containerPort":9090}],"volumeMounts":[{"mountPath":"/ca","name":"ca","readOnly":true},{"mountPath":"/metric-proxy-certs","name":"metric-proxy-certs","readOnly":true}]}],"serviceAccountName":"metric-proxy","volumes":[{"name":"ca","secret":{"secretName":"metric-proxy-ca-ver-1"}},{"name":"metric-proxy-certs","secret":{"secretName":"metric-proxy-cert-ver-1"}}]}}}}'
    kapp.k14s.io/original-diff-md5: 6dbe83dfe9afc45a899f3a89e4d0297d
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"metric-proxy"},"name":"metric-proxy","namespace":"cf-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"metric-proxy"}},"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"9090","prometheus.io/scrape":"true"},"labels":{"app":"metric-proxy"}},"spec":{"containers":[{"env":[{"name":"ADDR","value":":8080"},{"name":"APP_SELECTOR","value":"cloudfoundry.org/guid"},{"name":"NAMESPACE","value":"cf-workloads"},{"name":"QUERY_TIMEOUT","value":"5"}],"image":"oratos/metrics-server:v1.0.0@sha256:266be9306a2cb1aa862b382bdc5b029e000efd25aa8c0ceab3fffa66cf6ab512","imagePullPolicy":"Always","name":"metric-proxy","ports":[{"containerPort":8080},{"containerPort":9090}]}],"serviceAccountName":"metric-proxy"}}}}
    traffic.sidecar.istio.io/excludeInboundPorts: 15090,9090
  creationTimestamp: "2020-08-26T07:56:07Z"
  generation: 7
  labels:
    app: metric-proxy
    kapp.k14s.io/app: "1598428386871241000"
    kapp.k14s.io/association: v1.19fde1e94b7fc26272a00c0d1d0decbc
  name: metric-proxy
  namespace: cf-system
  resourceVersion: "6620012"
  selfLink: /apis/apps/v1/namespaces/cf-system/deployments/metric-proxy
  uid: 5b55af00-c469-48a0-8f27-e509c36c4993
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: metric-proxy
      kapp.k14s.io/app: "1598428386871241000"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: metric-proxy
        kapp.k14s.io/app: "1598428386871241000"
        kapp.k14s.io/association: v1.19fde1e94b7fc26272a00c0d1d0decbc
    spec:
      containers:
      - env:
        - name: ADDR
          value: :8080
        - name: APP_SELECTOR
          value: cloudfoundry.org/guid
        - name: NAMESPACE
          value: cf-workloads
        - name: QUERY_TIMEOUT
          value: "5"
        - name: CA_PATH
          value: /ca/tls.crt
        - name: CERT_PATH
          value: /metric-proxy-certs/tls.crt
        - name: KEY_PATH
          value: /metric-proxy-certs/tls.key
        image: oratos/metric-proxy@sha256:266be9306a2cb1aa862b382bdc5b029e000efd25aa8c0ceab3fffa66cf6ab512
        imagePullPolicy: Always
        name: metric-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ca
          name: ca
          readOnly: true
        - mountPath: /metric-proxy-certs
          name: metric-proxy-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metric-proxy
      serviceAccountName: metric-proxy
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ca
        secret:
          defaultMode: 420
          secretName: metric-proxy-ca-ver-1
      - name: metric-proxy-certs
        secret:
          defaultMode: 420
          secretName: metric-proxy-cert-ver-1
```

**Comment by heycait** [comment] 2020-09-11 15:13
Ahh ok the annotation actually needs to be in the pod spec section next to the prometheus annotations.

**Comment by kkburr** [comment] 2020-10-19 21:34
@PavanVasist , we recently fixed this, it should be in the latest cf-for-k8s. If you are deploying Prometheus via [cf-k8s-prometheus](https://github.com/cloudfoundry/cf-k8s-prometheus), you should be able to see metric-proxy metrics in prometheus.

**Closed by kkburr** 2020-10-19 21:34 UTC
Labels: unscheduled
